name: Build Electron App Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project (TS + copy HTML)
        run: npm run build

      - name: Package app with electron-builder
        run: npm run package

      - name: Upload Linux build artifact
        uses: actions/upload-artifact@v4
        with:
          name: electron-linux-build
          path: dist/*.AppImage
